### ISSUE TITLE
Sistema CRUD con JWT

### ISSUE THREAD

**Issue by popularizan** [santimacnet/WebAPI-Segura-JWT#4]
Donde podría encontrar mas información para montar un sistema CRUD con JWT y desde el cliente poder hacer las llamadas. ¿ Hay algún código de ejemplo del cliente para cuando expira el token volver a obtener otro para cuando vuelves a hacer alguna operacion CRUD?

**Comment by frpatino6** [comment]
Para el tema del vencimiento del token, desde el lado del cliente, cuando el api le retorne 401, es porque no está autorizado o el token ya venció, en ese momento puede hacer un request para generar el token de nuevo

**Comment by santimacnet** [comment]
> 
> 
> Donde podría encontrar mas información para montar un sistema CRUD con JWT y desde el cliente poder hacer las llamadas. ¿ Hay algún código de ejemplo del cliente para cuando expira el token volver a obtener otro para cuando vuelves a hacer alguna operacion CRUD?

Hola, en este ejemplo no se esta utilizando Refresh Tokens, cuando se expira el JWT se tiene que volver a realizar login para obtener un nuevo token valido.

Si estas interesado, en el mundo .NET la recomendación es usar: https://identityserver4.readthedocs.io/en/latest
